CREATE TABLE IF NOT EXISTS `program_studi` (
  `program_studi_id` VARCHAR(2) NOT NULL,
  `nama` VARCHAR(50) NULL,
  `jenjang` VARCHAR(50) NULL,
  `sort_order` INT NULL,
  `default_data` TINYINT(1) NULL DEFAULT 0,
  `waktu_buat` DATETIME NULL,
  `waktu_ubah` DATETIME NULL,
  `admin_buat` BIGINT NULL,
  `admin_ubah` BIGINT NULL,
  `ip_buat` VARCHAR(50) NULL,
  `ip_ubah` VARCHAR(50) NULL,
  `aktif` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`program_studi_id`))
ENGINE = InnoDB;

INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11608', 'TEKNIK TRANSFUSI DARAH', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20601', 'ELEKTRONIKA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20602', 'TELEKOMUNIKASI', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20603', 'TEKNIK LISTRIK', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21601', 'TEKNIK MESIN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('23601', 'ARSITEKTUR', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('24604', 'TEKNIK TEKSTIL', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32604', 'FIRE AND SAFETY', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('35601', 'SURVAI DAN PEMETAAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('44601', 'MATEMATIKA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('46601', 'LINGKUNGAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('55601', 'TEKNIK INFORMATIKA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('56601', 'TEKNIK KOMPUTER', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57601', 'MANAJEMEN INFORMATIKA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57602', 'KOMPUTERISASI AKUNTANSI', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61601', 'MANAJEMEN ADMINISTRASI', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61602', 'MANAJEMEN PERDAGANGAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61603', 'MANAJEMEN PERPAJAKAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61604', 'MANAJEMEN PEMASARAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61605', 'MANAJEMEN PERUSAHAAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61606', 'KEUANGAN DAN PERBANKAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('62601', 'AKUNTANSI', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63611', 'ADMINISTRASI BISNIS', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63612', 'SEKRETARI', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63621', 'PERPAJAKAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79602', 'BAHASA INGGRIS', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79604', 'BAHASA JEPANG', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79608', 'BAHASA BELANDA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90621', 'DESAIN INTERIOR', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90641', 'DESAIN KOMUNIKASI VISUAL', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91661', 'FILM DAN TELEVISI', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93601', 'PEMANDU WISATA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93602', 'PERHOTELAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93603', 'DIVISI KAMAR', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94605', 'TATA BUSANA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94606', 'TATA HIDANGAN', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94607', 'TATA BOGA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94608', 'TATA RIAS', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94609', 'GROUND HANDLING', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94610', 'PRAMUGARI-PRAMUGARA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94611', 'CARGO UDARA', 'D1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20501', 'ELEKTRONIKA', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21501', 'TEKNIK MESIN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22503', 'KONSTRUKSI GEDUNG', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54533', 'AGRIBISNIS PETERNAKAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54534', 'TEKNOLOGI HASIL TERNAK', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54555', 'PENYULUHAN KEHUTANAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('56501', 'TEKNIK KOMPUTER', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57501', 'MANAJEMEN INFORMATIKA', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57502', 'KOMPUTERISASI AKUNTANSI', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61501', 'MANAJEMEN ADMINISTRASI', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61504', 'MANAJEMEN PEMASARAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61505', 'MANAJEMEN PERUSAHAAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61506', 'KEUANGAN DAN PERBANKAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('62501', 'AKUNTANSI', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63501', 'ADMINISTRASI NEGARA', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63511', 'ADMINISTRASI NIAGA', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63512', 'KESEKRETARIATAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63521', 'PERPAJAKAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('71501', 'PERPUSTAKAAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79502', 'BAHASA INGGRIS', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('85501', 'PENDIDIKAN GURU PENJASKESREK', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86506', 'PENDIDIKAN GURU SEKOLAH DASAR', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86507', 'PENDIDIKAN GURU TAMAN KANAK-KANAK', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88501', 'PENDIDIKAN BAHASA DAN SASTRA INDONESIA', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90501', 'SENI RUPA', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90541', 'DESAIN KOMUNIKASI VISUAL', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91511', 'SENI KARAWITAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91531', 'PENATA TARI', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93501', 'PEMANDU WISATA', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93502', 'PERHOTELAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93503', 'DIVISI KAMAR', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94505', 'TATA BUSANA', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94506', 'TATA HIDANGAN', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94507', 'TATA BOGA', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94508', 'TATA RIAS', 'D2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11401', 'FISIOTERAPI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11402', 'RADIODIAGNOSTIK DAN RADIOTERAPI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11403', 'OKUPASI TERAPI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11404', 'REFRAKSI OPTISI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11406', 'PENGOBATAN TRADISIONAL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11407', 'AKUPUNKTUR', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11408', 'TEKNIK KARDIOVASCULER', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11409', 'MALARIOLOGI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12401', 'TEKNIK GIGI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13411', 'GIZI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13421', 'EPIDEMIOLOGI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13431', 'PROMOSI DAN PERILAKU KESEHATAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13441', 'HIPERKES DAN KESELAMATAN KERJA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13451', 'KESEHATAN LINGKUNGAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13452', 'ANALIS LINGKUNGAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13453', 'ANALIS KESEHATAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13461', 'ADMINISTRASI RUMAH SAKIT', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13462', 'PEREKAM DAN INFORMASI KESEHATAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('14401', 'KEPERAWATAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('15401', 'KEBIDANAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20401', 'TEKNIK ELEKTRONIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20402', 'TEKNIK TELEKOMUNIKASI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20403', 'TEKNIK LISTRIK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21401', 'TEKNIK MESIN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21402', 'MESIN INDUSTRI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21403', 'MESIN OTOMOTIF', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21404', 'MESIN PERKAKAS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21405', 'TEKNIK PENDINGIN DAN TATA UDARA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21406', 'TEKNIK KONVERSI ENERGI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21407', 'TEKNIK MANUFAKTUR', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21408', 'PERAWATAN DAN PERBAIKAN MESIN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21409', 'PERANCANGAN MEKANIK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21410', 'PENGECORAN LOGAM', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21411', 'TEKNIK PERANCANGAN MANUFAKTUR', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21412', 'TEKNIK MEKATRONIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21413', 'ALAT BERAT', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21414', 'POLA PENGECORAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22401', 'TEKNIK SIPIL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22402', 'TEKNIK KONSTRUKSI SIPIL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22403', 'TEKNIK KONSTRUKSI GEDUNG', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22404', 'TEKNIK SIPIL BANGUNAN AIR', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22405', 'TEKNIK SIPIL BANGUNAN TRANSPORTASI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22406', 'TEKNIK JALAN RAYA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('23401', 'ARSITEKTUR', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('24401', 'TEKNIK KIMIA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('24402', 'ANALIS KIMIA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('24403', 'PETRO DAN OLEO KIMIA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('24404', 'TEKNIK INDUSTRI TEKSTIL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('25401', 'TEKNIK LINGKUNGAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('26401', 'TEKNIK INDUSTRI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('26402', 'MANAJEMEN INDUSTRI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('27401', 'METALURGI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('28401', 'MATERIAL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('29401', 'TEKNIK GEODESI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('30401', 'FISIKA INSTRUMENTASI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('31401', 'TEKNIK PERTAMBANGAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32401', 'EKSPLORASI MINYAK DAN GAS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32402', 'PENGOLAHAN MINYAK DAN GAS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32403', 'LABORATORIUM MINYAK DAN GAS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32404', 'KESELAMATAN KERJA DAN PENCEGAHAN KEBAKARAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32405', 'INSTRMENTASI DAN ELEKTRONIKA MIGAS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('34401', 'GEOLOGI TERAPAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('35401', 'SURVAI DAN PEMETAAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('36401', 'TEKNIK PERANCANGAN DAN KONSTRUKSI KAPAL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('36402', 'TEKNIK PERMESINAN KAPAL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('36403', 'TEKNIK BANGUNAN KAPAL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('36404', 'TEKNIK KELISTRIKAN KAPAL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('38401', 'TEKNIK KELAUTAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('39401', 'TRANSPORTASI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('40401', 'LISTRIK PESAWAT', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('40402', 'AERONAUTIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('40403', 'RANGKA PESAWAT', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('40404', 'MOTOR PESAWAT', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('40405', 'AVIONIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('40406', 'TEKNIK & MANAJEMEN LOGISTIK PENERBANGAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41401', 'MESIN DAN PERALATAN PERTANIAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41402', 'TATA AIR PERTANIAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41411', 'TEKNOLOGI INDUSTRI PERTANIAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41421', 'TEKNOLOGI PANGAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41431', 'TEKNOLOGI PRODUKSI PERTANIAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41432', 'TEKNOLOGI PRODUKSI HORTIKULTURA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41433', 'TEKNOLOGI PRODUKSI PERKEBUNAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41434', 'TEKNOLOGI PRODUKSI PERIKANAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('44401', 'MATEMATIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('45401', 'FISIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('46401', 'BIOLOGI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('47401', 'KIMIA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('48401', 'FARMASI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('48402', 'ANALIS FARMASI DAN MAKANAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('49401', 'STATISTIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('51401', 'GEOGRAFI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('51411', 'PENGINDERAAN JAUH DAN SIG', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54401', 'SOSIAL EKONOMI PERTANIAN (AGROBISNIS)', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54403', 'PENYULUHAN DAN KOMUNIKASI PERTANIAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54411', 'AGRONOMI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54412', 'HORTIKULTURA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54413', 'PEMULIAAN TANAMAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54414', 'ARSITEKTUR LANSEKAP', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54415', 'ILMU TANAH', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54416', 'BUDIDAYA PERTANIAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54417', 'HAMA DAN PENYAKIT TUMBUHAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54431', 'NUTRISI DAN MAKANAN TERNAK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54432', 'PRODUKSI TERNAK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54433', 'BUDIDAYA TERNAK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54434', 'TEKNOLOGI HASIL TERNAK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54435', 'SOSIAL EKONOMI PETERNAKAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54442', 'SUMBER DAYA PERAIRAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54443', 'BUDIDAYA PERAIRAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54444', 'TEKNOLOGI HASIL PERIKANAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54445', 'AGRIBISNIS PERIKANAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54446', 'PEMANFAATAN SUMBER DAYA PERIKANAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54451', 'TEKNOLOGI HASIL HUTAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54452', 'BUDIDAYA HUTAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54453', 'KONSERVASI SUMBER DAYA HUTAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54454', 'MANAJEMEN HUTAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54457', 'MANAJEMEN PERKEBUNAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54461', 'KESEHATAN HEWAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54471', 'BUDIDAYA TANAMAN PERKEBUNAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('55401', 'TEKNIK INFORMATIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('56401', 'TEKNIK KOMPUTER', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57401', 'MANAJEMEN INFORMATIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57402', 'KOMPUTERISASI AKUNTANSI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61401', 'MANAJEMEN ADMINISTRASI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61402', 'MANAJEMEN PERDAGANGAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61403', 'MANAJEMEN PERPAJAKAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61404', 'MANAJEMEN PEMASARAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61405', 'MANAJEMEN PERUSAHAAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61406', 'KEUANGAN DAN PERBANKAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61407', 'MANAJEMEN TRANSPORTASI LAUT', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61408', 'MANAJEMEN TRANSPORTASI UDARA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('62401', 'AKUNTANSI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63401', 'ADMINISTRASI NEGARA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63411', 'ADMINISTRASI BISNIS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63412', 'SEKRETARI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63413', 'ADMINISTRASI KEUANGAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63414', 'ADMINISTRASI LOGISTIK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63421', 'ADMINISTRASI PERPAJAKAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('64401', 'HUBUNGAN INTERNASIONAL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('65401', 'ADMINISTRASI PEMERINTAHAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('68401', 'PEMBANGUNAN MASYARAKAT DESA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('70401', 'HUBUNGAN MASYARAKAT', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('70402', 'JURNALISTIK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('70403', 'KOMUNIKASI MASSA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('70404', 'PERIKLANAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('70405', 'PENYIARAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('71401', 'PERPUSTAKAAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('71402', 'KEARSIPAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('72401', 'PEKERJA SOSIAL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('74401', 'ADMINISTRASI PERADILAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('75401', 'FILSAFAT TEOLOGI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79401', 'BAHASA INDONESIA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79402', 'BAHASA INGGRIS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79403', 'BAHASA ARAB', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79404', 'BAHASA JEPANG', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79405', 'BAHASA PERANCIS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79406', 'BAHASA JERMAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79407', 'BAHASA RUSIA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79408', 'BAHASA BELANDA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79409', 'BAHASA MANDARIN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79410', 'BAHASA KOREA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84402', 'PENDIDIKAN MATEMATIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84403', 'PENDIDIKAN FISIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84405', 'PENDIDIKAN BIOLOGI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('85401', 'PENDIDIKAN JASMANI, KESEHATAN DAN REKREASI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86408', 'PENDIDIKAN GURU AGAMA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87402', 'PENDIDIKAN GEOGRAFI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87403', 'PENDIDIKAN EKONOMI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88401', 'PENDIDIKAN BAHASA DAN SASTRA INDONESIA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88403', 'PENDIDIKAN BAHASA INGGRIS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88405', 'PENDIDIKAN BAHASA JEPANG', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90401', 'SENI RUPA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90411', 'KRIYA KAIN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90412', 'KRIYA KAYU', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90413', 'KRIYA KERAMIK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90414', 'KRIYA LOGAM', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90415', 'KRIYA KULIT', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90416', 'KRIYA PERHIASAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90417', 'KRIYA SENI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90421', 'DESAIN INTERIOR', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90431', 'DESAIN PRODUK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90441', 'DESAIN KOMUNIKASI VISUAL', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90442', 'DESAIN GRAFIS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90443', 'KOMPUTER MULTIMEDIA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90444', 'TEKNIK GRAFIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91411', 'SENI KARAWITAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91421', 'SENI MUSIK', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91431', 'SENI TARI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91441', 'SENI PEDALANGAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91451', 'SENI TEATER', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91461', 'TELEVISI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91462', 'FILM', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91471', 'FOTOGRAFI', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91481', 'RADIO', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('92401', 'KETATALAKSANAAN PELAYARAN NIAGA DAN KEPELABUHAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('92402', 'TEKNIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('92403', 'NAUTIKA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93401', 'USAHA PERJALANAN WISATA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93402', 'PERHOTELAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93403', 'PARIWISATA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94401', 'ASURANSI JIWA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94402', 'ASURANSI KESEHATAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94403', 'ASURANSI KERUGIAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94404', 'TERAPI WICARA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94405', 'TATA BUSANA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94406', 'TATA BOGA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94407', 'TATA GRIYA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94408', 'TATA RIAS', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94409', 'ADMINISTRASI ASURANSI DAN AKTUARIA', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95403', 'PERENCANAAN DAN MONITORING PEMBANGUNAN', 'D3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11301', 'FISIOTERAPI', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11306', 'PENGOBATAN TRADISIONAL CINA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13341', 'KESEHATAN DAN KESELAMATAN KERJA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13353', 'ANALIS KESEHATAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('14301', 'PERAWAT PENDIDIK', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('15301', 'BIDAN PENDIDIK', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20301', 'TEKNIK ELEKTRONIKA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20302', 'TEKNIK TELEKOMUNIKASI', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20303', 'TEKNIK LISTRIK', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20304', 'TEKNIK TELEKOMUNIKASI NIRKABEL', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21301', 'TEKNIK MESIN PRODUKSI DAN PERAWATAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21303', 'TEKNIK OTOMOTIF ELEKTRONIK', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21306', 'TEKNIK KONSERVASI KONVERSI ENERGI', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21307', 'TEKNIK MANUFAKTUR', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21312', 'TEKNIK MEKATRONIKA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22301', 'PERANCANGAN JALAN DAN JEMBATAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22302', 'MANAJEMEN REKAYASA KONSTRUKSI', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22303', 'TEKNIK PERUMAHAN DAN PEMUKIMAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22304', 'TEKNIK BANGUNAN RAWA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('24301', 'TEKNOLOGI KIMIA INDUSTRI', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('26302', 'TEKNIK MANAJEMEN PABRIK', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('26303', 'TEKNOLOGI MEKANIK INDUSTRI', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32304', 'TEKNIK KESEHATAN DAN KESELAMATAN KERJA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('39301', 'TRANSPORTASI', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41311', 'TEKNOLOGI INDUSTRI PERTANIAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41331', 'TEKNOLOGI PRODUKSI PERTANIAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41333', 'TEKNOLOGI PENGOLAHAN HASIL PERKEBUNAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54312', 'TEKNOLOGI INDUSTRI HORTIKULTURA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54331', 'TEKNOLOGI PAKAN TERNAK', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54357', 'MANAJEMEN PERKEBUNAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54371', 'BUDIDAYA PERKEBUNAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('55301', 'TEKNIK INFORMATIKA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('56301', 'TEKNIK KOMPUTER', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57301', 'MANAJEMEN INFORMATIKA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57302', 'KOMPUTERISASI AKUNTANSI', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61304', 'MANAJEMEN PEMASARAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61306', 'KEUANGAN DAN PERBANKAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61307', 'MANAJEMEN ASET', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('62301', 'AKUNTANSI', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63301', 'ADMINISTRASI NEGARA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63311', 'ADMINISTRASI BISNIS', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63312', 'KESEKRETARIATAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('65301', 'ADMINISTRASI PEMERINTAHAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('70302', 'JURNALISTIK', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('71302', 'KEARSIPAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83313', 'PENDIDIKAN TATA RIAS', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90331', 'DESAIN PRODUK', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90342', 'DESAIN GRAFIS', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90343', 'KOMPUTER MULTIMEDIA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90344', 'TEKNIK GRAFIKA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('92301', 'KETATALAKSANAAN PELAYARAN NIAGA DAN KEPELABUHAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93301', 'USAHA PERJALANAN WISATA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93302', 'PERHOTELAN', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93303', 'PARIWISATA', 'D4', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11201', 'PENDIDIKAN DOKTER', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11202', 'FISIOTERAPI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12201', 'PENDIDIKAN DOKTER GIGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13201', 'KESEHATAN MASYARAKAT', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13211', 'ILMU GIZI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13241', 'KESEHATAN DAN KESELAMATAN KERJA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13251', 'KESEHATAN LINGKUNGAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13261', 'ADMINISTRASI RUMAH SAKIT', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('14201', 'ILMU KEPERAWATAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('15201', 'KEBIDANAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20201', 'TEKNIK ELEKTRO', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21201', 'TEKNIK MESIN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22201', 'TEKNIK SIPIL', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('23201', 'ARSITEKTUR', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('24201', 'TEKNIK KIMIA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('25201', 'TEKNIK LINGKUNGAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('26201', 'TEKNIK INDUSTRI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('27201', 'TEKNIK METALURGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('28201', 'TEKNIK MATERIAL', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('29201', 'TEKNIK GEODESI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('30201', 'FISIKA TEKNIK', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('31201', 'TEKNIK PERTAMBANGAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32201', 'TEKNIK PERMINYAKAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('33201', 'TEKNIK GEOFISIKA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('33202', 'METEOROLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('34201', 'TEKNIK GEOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('35201', 'PERENCANAAN WILAYAH DAN KOTA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('36201', 'TEKNIK PERKAPALAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('36202', 'TEKNIK SISTEM PERKAPALAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('37201', 'TEKNIK NUKLIR', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('38201', 'TEKNIK KELAUTAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('39201', 'TRANSPORTASI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('40201', 'TEKNIK PENERBANGAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41201', 'TEKNIK PERTANIAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41211', 'TEKNOLOGI INDUSTRI PERTANIAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41221', 'TEKNOLOGI PANGAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41231', 'TEKNOLOGI HASIL PERTANIAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41234', 'TEKNOLOGI PENGOLAHAN HASIL PERIKANAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('44201', 'MATEMATIKA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('45201', 'FISIKA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('46201', 'BIOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('46202', 'MIKROBIOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('47201', 'KIMIA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('48201', 'FARMASI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('48202', 'FARMASI KLINIK DAN KOMUNITAS', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('49201', 'STATISTIKA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('50201', 'ASTRONOMI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('51201', 'GEOGRAFI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('51211', 'KARTOGRAFI DAN PENGINDERAAN JAUH', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54201', 'AGRIBISNIS', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54211', 'AGROTEKNOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54231', 'PETERNAKAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54241', 'ILMU KELAUTAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54242', 'MANAJEMEN SUMBER DAYA PERAIRAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54243', 'BUDIDAYA PERAIRAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54244', 'TEKNOLOGI HASIL PERIKANAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54245', 'AGROBISNIS PERIKANAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54246', 'PEMANFAATAN SUMBER DAYA PERIKANAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54251', 'KEHUTANAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54261', 'PENDIDIKAN DOKTER HEWAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54271', 'BUDIDAYA PERKEBUNAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('55201', 'TEKNIK INFORMATIKA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('56201', 'SISTEM KOMPUTER', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57201', 'SISTEM INFORMASI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('60201', 'EKONOMI PEMBANGUNAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61201', 'MANAJEMEN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('62201', 'AKUNTANSI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63201', 'ILMU ADMINISTRASI NEGARA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63211', 'ILMU ADMINISTRASI NIAGA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63221', 'ILMU ADMINISTRASI PERPAJAKAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('64201', 'HUBUNGAN INTERNASIONAL', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('65201', 'ILMU PEMERINTAHAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('66201', 'KRIMINOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('67201', 'ILMU POLITIK', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('68201', 'ILMU SOSIATRI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('69201', 'SOSIOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('70201', 'ILMU KOMUNIKASI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('71201', 'ILMU PERPUSTAKAAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('72201', 'ILMU KESEJAHTERAAN SOSIAL', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('73201', 'PSIKOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('74201', 'ILMU HUKUM', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('75201', 'ILMU FILSAFAT', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('76201', 'ILMU RELIGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('77201', 'ILMU TEOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79201', 'SASTRA INDONESIA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79202', 'SASTRA INGGRIS', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79203', 'SASTRA ARAB', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79204', 'SASTRA JEPANG', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79205', 'SASTRA PERANCIS', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79206', 'SASTRA JERMAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79207', 'SASTRA RUSIA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79208', 'SASTRA BELANDA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79209', 'SASTRA CINA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79210', 'SASTRA KOREA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79211', 'SASTRA DAERAH', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('80201', 'ILMU SEJARAH', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('81201', 'ILMU ARKEOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('82201', 'ANTROPOLOGI SOSIAL', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83201', 'PENDIDIKAN TEKNIK ELEKTRO', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83202', 'PENDIDIKAN TEKNIK ELEKTRONIKA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83203', 'PENDIDIKAN TEKNIK MESIN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83204', 'PENDIDIKAN TEKNIK OTOMOTIF', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83205', 'PENDIDIKAN TEKNIK BANGUNAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83206', 'PENDIDIKAN KESEJAHTERAAN KELUARGA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83207', 'PENDIDIKAN TEKNIK INFORMATIKA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83211', 'PENDIDIKAN TATA BOGA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83212', 'PENDIDIKAN TATA BUSANA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83213', 'PENDIDIKAN TATA RIAS', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84201', 'PENDIDIKAN IPA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84202', 'PENDIDIKAN MATEMATIKA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84203', 'PENDIDIKAN FISIKA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84204', 'PENDIDIKAN KIMIA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84205', 'PENDIDIKAN BIOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('85201', 'PENDIDIKAN JASMANI, KESEHATAN DAN REKREASI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('85202', 'PENDIDIKAN KEPELATIHAN OLAHRAGA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86201', 'BIMBINGAN KONSELING', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86202', 'PENDIDIKAN LUAR BIASA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86203', 'TEKNOLOGI PENDIDIKAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86204', 'ADMINISTRASI PENDIDIKAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86205', 'PENDIDIKAN LUAR SEKOLAH', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86206', 'PENDIDIKAN GURU SEKOLAH DASAR', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86207', 'PENDIDIKAN GURU PENDIDIKAN ANAK USIA DINI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86208', 'PENDIDIKAN GURU AGAMA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86209', 'PJJ PENDIDIKAN GURU SEKOLAH DASAR', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87201', 'PENDIDIKAN SEJARAH', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87202', 'PENDIDIKAN GEOGRAFI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87203', 'PENDIDIKAN EKONOMI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87204', 'PENDIDIKAN SOSIOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87205', 'PENDIDIKAN PANCASILA DAN KEWARGANEGARAAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87220', 'PENDIDIKAN IPS', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88201', 'PENDIDIKAN BAHASA DAN SASTRA INDONESIA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88202', 'PENDIDIKAN BAHASA DAN SASTRA DAERAH', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88203', 'PENDIDIKAN BAHASA INGGRIS', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88204', 'PENDIDIKAN BAHASA ARAB', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88205', 'PENDIDIKAN BAHASA JEPANG', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88206', 'PENDIDIKAN BAHASA PERANCIS', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88207', 'PENDIDIKAN BAHASA JERMAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88208', 'PENDIDIKAN BAHASA MANDARIN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88209', 'PENDIDIKAN SENI DRAMA, TARI DAN MUSIK', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88210', 'PENDIDIKAN SENI RUPA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('89201', 'ILMU KEOLAHRAGAAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90201', 'SENI RUPA MURNI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90211', 'KRIYA SENI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90221', 'DESAIN INTERIOR', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90231', 'DESAIN PRODUK', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90241', 'DESAIN KOMUNIKASI VISUAL', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90242', 'DESAIN GRAFIS', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91201', 'ETNOMUSIKOLOGI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91202', 'ANTROPOLOGI TARI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91211', 'SENI KARAWITAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91221', 'SENI MUSIK', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91231', 'SENI TARI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91241', 'SENI PEDALANGAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91251', 'SENI TEATER', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91261', 'TELEVISI DAN FILM', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91271', 'FOTOGRAFI', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91281', 'RADIO', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('92201', 'KETATALAKSANAAN PELAYARAN NIAGA DAN KEPELABUHAN', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93201', 'USAHA PERJALANAN WISATA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('93202', 'PERHOTELAN DAN PARIWISATA', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95203', 'PEMBANGUNAN WILAYAH', 'S1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11101', 'ILMU KEDOKTERAN DASAR', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11102', 'ILMU KEDOKTERAN KELUARGA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11103', 'ILMU KEDOKTERAN KLINIS', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11104', 'ILMU KEDOKTERAN TROPIS', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11105', 'IMUNOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11106', 'BIOMEDIK', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11107', 'PULMONOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11108', 'ERGONOMI FISIOLOGI KERJA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11109', 'PENDIDIKAN DOKTER', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11122', 'ILMU KESEHATAN OLAH RAGA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11123', 'TEKNOLOGI BIOMEDIS', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11124', 'ILMU FORENSIK', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12101', 'ILMU KEDOKTERAN GIGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12102', 'ILMU KEDOKTERAN GIGI DASAR', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12103', 'ILMU KEDOKTERAN GIGI KOMUNITAS', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13101', 'ILMU KESEHATAN MASYARAKAT', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13111', 'ILMU GIZI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13121', 'EPIDEMIOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13122', 'KESEHATAN REPRODUKSI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13131', 'PROMOSI KESEHATAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13141', 'KESEHATAN DAN KESELAMATAN KERJA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13151', 'KESEHATAN LINGKUNGAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13161', 'ADMINISTRASI RUMAH SAKIT', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13163', 'ADMINISTRASI KEBIJAKAN KESEHATAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('14101', 'ILMU KEPERAWATAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('15101', 'KEBIDANAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20101', 'TEKNIK ELEKTRO', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20102', 'OPTO ELEKTRONIKA LASER', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20103', 'INSTRUMENTASI DAN KONTROL', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21101', 'TEKNIK MESIN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22101', 'TEKNIK SIPIL', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22102', 'SISTEM DAN TEKNIK JALAN RAYA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('23101', 'ARSITEKTUR', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('24101', 'TEKNIK KIMIA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('25101', 'TEKNIK LINGKUNGAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('25102', 'ILMU LINGKUNGAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('25103', 'TEKNIK AIR TANAH', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('26101', 'TEKNIK INDUSTRI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('27101', 'TEKNIK METALURGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('28101', 'TEKNIK MATERIAL', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('29101', 'TEKNIK GEODESI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('30101', 'FISIKA TEKNIK', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('31101', 'TEKNIK PERTAMBANGAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32101', 'TEKNIK PERMINYAKAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('33101', 'TEKNIK GEOFISIKA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('34101', 'TEKNIK GEOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('34102', 'SAINS KEBUMIAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('35101', 'PERENCANAAN WILAYAH DAN KOTA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('35102', 'RANCANG KOTA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('36101', 'TEKNIK PERKAPALAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('37101', 'ILMU DAN REKAYASA NUKLIR', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('38101', 'TEKNIK KELAUTAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('39101', 'TRANSPORTASI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('40101', 'TEKNIK PENERBANGAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41101', 'TEKNIK PERTANIAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41111', 'TEKNOLOGI INDUSTRI PERTANIAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41121', 'ILMU DAN TEKNOLOGI PANGAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41131', 'TEKNOLOGI HASIL PERTANIAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41133', 'TEKNOLOGI HASIL PERKEBUNAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('44101', 'MATEMATIKA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('45101', 'FISIKA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('46101', 'BIOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('47101', 'KIMIA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('48101', 'FARMASI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('49101', 'STATISTIKA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('50101', 'ASTRONOMI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('51101', 'GEOGRAFI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('51111', 'PENGINDERAAN JAUH', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54101', 'AGRIBISNIS', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54102', 'EKONOMI PERTANIAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54103', 'PENYULUHAN DAN KOMUNIKASI PEMBANGUNAN PERTANIAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54104', 'AGRONOMI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54105', 'ILMU TANAH', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54106', 'ILMU HAMA DAN PENYAKIT TUMBUHAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54107', 'PEMULIAAN TANAMAN DAN BIOTEKNOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54108', 'ILMU PERTANIAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54110', 'AGROKLIMATOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54131', 'PETERNAKAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54132', 'BIOLOGI REPRODUKSI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54141', 'ILMU KELAUTAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54142', 'SUMBER DAYA PERAIRAN PESISIR DAN KELAUTAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54143', 'BUDIDAYA PERAIRAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54145', 'AGRIBISNIS PERIKANAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54146', 'MANAJEMEN SUMBER DAYA PERAIRAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54147', 'ILMU PERAIRAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54151', 'ILMU KEHUTANAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54153', 'KONSERVASI SUMBER DAYA LAHAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54157', 'MANAJEMEN PERKEBUNAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54162', 'KESEHATAN MASYARAKAT VETERINER', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('55101', 'TEKNIK INFORMATIKA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('56101', 'SISTEM KOMPUTER', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('57101', 'SISTEM INFORMASI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('60101', 'ILMU EKONOMI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61101', 'MANAJEMEN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('62101', 'AKUNTANSI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63101', 'ILMU ADMINISTRASI NEGARA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63111', 'ILMU ADMINISTRASI NIAGA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('64101', 'ILMU HUBUNGAN INTERNASIONAL', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('65101', 'ILMU PEMERINTAHAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('66101', 'KRIMINOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('67101', 'ILMU POLITIK', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('68101', 'ILMU SOSIAL', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('69101', 'SOSIOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('70101', 'ILMU KOMUNIKASI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('71101', 'ILMU PERPUSTAKAAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('72101', 'ILMU KESEJAHTERAAN SOSIAL', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('73101', 'PSIKOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('74101', 'ILMU HUKUM', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('74102', 'KENOTARIATAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('75101', 'ILMU FILSAFAT', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('76101', 'ILMU RELIGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('77101', 'ILMU TEOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79101', 'ILMU SUSASTRA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79102', 'ILMU LINGUISTIK', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79103', 'BAHASA INGGRIS', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('80101', 'ILMU SEJARAH', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('81101', 'ILMU ARKEOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('82101', 'ANTROPOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83101', 'PENDIDIKAN TEKNOLOGI DAN KEJURUAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84101', 'PENDIDIKAN IPA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84102', 'PENDIDIKAN MATEMATIKA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84103', 'PENDIDIKAN FISIKA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84104', 'PENDIDIKAN KIMIA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84105', 'PENDIDIKAN BIOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('85101', 'PENDIDIKAN OLAHRAGA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86101', 'BIMBINGAN KONSELING', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86102', 'PENDIDIKAN LUAR BIASA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86103', 'TEKNOLOGI PENDIDIKAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86104', 'ADMINISTRASI PENDIDIKAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86105', 'PENDIDIKAN LUAR SEKOLAH', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86106', 'PENDIDIKAN GURU SEKOLAH DASAR', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86107', 'PENDIDIKAN GURU PENDIDIKAN ANAK USIA DINI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86108', 'PENDIDIKAN GURU AGAMA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86120', 'PENELITIAN DAN EVALUASI PENDIDIKAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86121', 'PENGEMBANGAN KURIKULUM', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86122', 'PENDIDIKAN DASAR', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87101', 'PENDIDIKAN SEJARAH', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87102', 'PENDIDIKAN GEOGRAFI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87103', 'PENDIDIKAN EKONOMI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87104', 'PENDIDIKAN SOSIOLOGI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87120', 'PENDIDIKAN IPS', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88101', 'PENDIDIKAN BAHASA DAN SASTRA INDONESIA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88102', 'PENDIDIKAN BAHASA DAN SASTRA DAERAH', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88103', 'PENDIDIKAN BAHASA INGGRIS', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88104', 'PENDIDIKAN BAHASA ARAB', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88105', 'PENDIDIKAN BAHASA JEPANG', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88106', 'PENDIDIKAN BAHASA PERANCIS', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88107', 'PENDIDIKAN BAHASA JERMAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88108', 'PENDIDIKAN BAHASA MANDARIN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88109', 'PENDIDIKAN SENI DRAMA, TARI DAN MUSIK', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88110', 'PENDIDIKAN SENI RUPA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88111', 'PENDIDIKAN BAHASA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('89101', 'ILMU KEOLAHRAGAAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90101', 'SENI RUPA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90102', 'DESAIN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90131', 'DESAIN PRODUK', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91101', 'PENCIPTAAN DAN PENGKAJIAN SENI', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('94101', 'AKTUARIA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95101', 'ILMU PENGELOLAAN SUMBER DAYA ALAM DAN LINGKUNGA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95102', 'KAJIAN KEPENDUDUKAN DAN KETENAGAKERJAAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95103', 'ILMU PERENC PEMBANGUNAN WILAYAH DAN PEDESAAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95104', 'KAJIAN PARIWISATA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95105', 'ADMINISTRASI PEMBANGUNAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95106', 'PENGEMBANGAN SUMBER DAYA MANUSIA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95107', 'STUDI KEBIJAKAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95120', 'KAJIAN ILMU KEPOLISIAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95121', 'KAJIAN WILAYAH AMERIKA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95122', 'KAJIAN WILAYAH JEPANG', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95123', 'KAJIAN WILAYAH EROPA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95124', 'KAJIAN TIMUR TENGAH DAN ISLAM', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95125', 'KAJIAN PENGEMBANGAN PERKOTAAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95126', 'KAJIAN WANITA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95127', 'KAJIAN BUDAYA', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95128', 'KAJIAN KETAHANAN NASIONAL', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95129', 'KAJIAN ILMU LINGKUNGAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95130', 'JENDER DAN PEMBANGUNAN', 'S2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11001', 'ILMU KEDOKTERAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11002', 'ILMU KEDOKTERAN DASAR', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11006', 'BIOMEDIK', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12001', 'ILMU KEDOKTERAN GIGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13001', 'ILMU KESEHATAN MASYARAKAT', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13011', 'ILMU GIZI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('13021', 'EPIDEMIOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('14001', 'ILMU KEPERAWATAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20001', 'ILMU TEKNIK ELEKTRO', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('20002', 'OPTO ELEKTRONIKA LASER', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('21001', 'ILMU TEKNIK MESIN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('22001', 'ILMU TEKNIK SIPIL', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('23001', 'ILMU ARSITEKTUR', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('24001', 'ILMU TEKNIK KIMIA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('25001', 'ILMU TEKNIK LINGKUNGAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('26001', 'TEKNIK INDUSTRI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('27001', 'TEKNIK METALURGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('28001', 'ILMU TEKNIK MATERIAL', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('29001', 'ILMU TEKNIK GEODESI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('30001', 'ILMU FISIKA TEKNIK', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('31001', 'ILMU TEKNIK PERTAMBANGAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('32001', 'ILMU TEKNIK PERMINYAKAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('33001', 'ILMU GEOFISIKA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('34001', 'ILMU TEKNIK GEOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('34002', 'SAINS KEBUMIAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('35001', 'ILMU PERENCANAAN WILAYAH DAN KOTA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('36001', 'ILMU TEKNIK PERKAPALAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('37001', 'ILMU DAN REKAYASA NUKLIR', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('38001', 'ILMU TEKNIK KELAUTAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('39001', 'ILMU TRANSPORTASI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('40001', 'ILMU TEKNIK PENERBANGAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41001', 'ILMU TEKNIK PERTANIAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41011', 'TEKNOLOGI INDUSTRI PERTANIAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41021', 'ILMU DAN TEKNOLOGI PANGAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('41031', 'TEKNOLOGI HASIL PERTANIAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('44001', 'ILMU MATEMATIKA DAN ILMU PENGETAHUAN ALAM', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('44002', 'ILMU MATEMATIKA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('45001', 'ILMU FISIKA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('46001', 'ILMU BIOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('47001', 'ILMU KIMIA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('48001', 'ILMU FARMASI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('49001', 'ILMU STATISTIK', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('50001', 'ILMU ASTRONOMI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('51001', 'ILMU GEOGRAFI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54001', 'ILMU PERTANIAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54002', 'ILMU EKONOMI PERTANIAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54003', 'PENYULUHAN DAN KOMUNIKASI PEMBANGUNAN PERTANIAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54004', 'AGRONOMI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54005', 'ILMU TANAH', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54010', 'AGROKLIMATOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54031', 'ILMU TERNAK', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54032', 'BIOLOGI REPRODUKSI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54041', 'ILMU KELAUTAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54042', 'MANAJEMEN SUMBER DAYA PERAIRAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54043', 'ILMU PERAIRAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54051', 'ILMU KEHUTANAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('55001', 'ILMU KOMPUTER', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('60001', 'ILMU EKONOMI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('61001', 'ILMU MANAJEMEN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('62001', 'ILMU AKUNTANSI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('63001', 'ILMU ADMINISTRASI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('65001', 'ILMU PEMERINTAHAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('66001', 'KRIMINOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('67001', 'ILMU POLITIK', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('68001', 'ILMU SOSIAL', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('69001', 'ILMU SOSIOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('70001', 'ILMU KOMUNIKASI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('72001', 'ILMU KESEJAHTERAAN SOSIAL', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('73001', 'ILMU PSIKOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('74001', 'ILMU HUKUM', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('75001', 'ILMU FILSAFAT', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('76001', 'ILMU RELIGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('77001', 'ILMU TEOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79001', 'ILMU SUSASTRA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('79002', 'ILMU LINGUISTIK', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('80001', 'ILMU SEJARAH', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('81001', 'ILMU ARKEOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('82001', 'ILMU ANTROPOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('83001', 'PENDIDIKAN TEKNOLOGI DAN KEJURUAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84001', 'PENDIDIKAN MIPA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84002', 'PENDIDIKAN MATEMATIKA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('84005', 'PENDIDIKAN BIOLOGI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('85001', 'PENDIDIKAN OLAHRAGA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86001', 'ILMU PENDIDIKAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86003', 'TEKNOLOGI PENDIDIKAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86004', 'ADMINISTRASI PENDIDIKAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86005', 'PENDIDIKAN LUAR SEKOLAH', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86011', 'PSIKOLOGI PENDIDIKAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86020', 'PENELITAN DAN EVALUASI PENDIDIKAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('86021', 'PENGEMBANGAN KURIKULUM', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87001', 'PENDIDIKAN IPS', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('87003', 'PENDIDIKAN EKONOMI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88001', 'ILMU PENDIDIKAN BAHASA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('88003', 'PENDIDIKAN BAHASA INGGRIS', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('89001', 'ILMU KEOLAHRAGAAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('90001', 'SENI RUPA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('91001', 'PENCIPTAAN DAN PENGKAJIAN SENI', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95001', 'ILMU PENGELOLAAN SUMBER DAYA ALAM DAN LINGKUNGA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95002', 'KAJIAN KEPENDUDUKAN DAN KETENAGAKERJAAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95003', 'ILMU PERENC PEMBANGUNAN WILAYAH DAN PEDESAAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95027', 'KAJIAN BUDAYA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95029', 'KAJIAN ILMU LINGKUNGAN', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('95031', 'ILMU-ILMU HUMANIORA', 'S3', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11701', 'ILMU PENYAKIT MATA', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11702', 'ILMU PENYAKIT DALAM', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11703', 'ILMU PENYAKIT SYARAF', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11704', 'ILMU PENYAKIT KULIT DAN KELAMIN', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11705', 'ILMU PENYAKIT THT', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11706', 'ILMU ANESTESI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11707', 'ILMU BEDAH', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11708', 'ILMU KEBIDANAN DAN PENYAKIT KANDUNGAN', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11709', 'ILMU PENYAKIT PARU', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11710', 'ILMU KEDOKTERAN FORENSIK', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11711', 'ILMU KESEHATAN ANAK', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11712', 'ILMU BEDAH ORTOPAEDI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11713', 'ILMU BEDAH UROLOGI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11714', 'ILMU BEDAH PLASTIK', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11715', 'ILMU PENYAKIT JANTUNG', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11717', 'ILMU BEDAH ANAK', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11718', 'ILMU PATOLOGI ANATOMI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11719', 'ILMU PATOLOGI KLINIK', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11720', 'ILMU KEDOKTERAN NUKLIR', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11721', 'ILMU KEDOKTERAN FISIK DAN REHABILITASI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11722', 'ILMU KEDOKTERAN OLAHRAGA', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11723', 'RADIOLOGI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11724', 'PSIKIATRI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11725', 'MIKROBIOLOGI KLINIK', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11726', 'FARMAKOLOGI KLINIK', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11727', 'ILMU KEDOKTERAN OKUPASI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11728', 'ORTHOPAEDIK DAN TRAUMATOLOGI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11729', 'ILMU BEDAH SYARAF', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11730', 'ILMU KEDOKTERAN KLINIS', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11731', 'BEDAH TORAK DAN KARDIOVASKULER', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12701', 'ILMU BEDAH MULUT', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12702', 'ILMU PENYAKIT MULUT', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12703', 'ILMU KONSERVASI GIGI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12704', 'ILMU KESEHATAN GIGI ANAK', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12705', 'PERIODONSIA', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12706', 'ORTODONSIA', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12707', 'PROSTODONSIA', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('14701', 'ILMU KEPERAWATAN', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('48701', 'FARMASI', 'Sp-1', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11802', 'ILMU PENYAKIT DALAM', 'Sp-2', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('11901', 'PROFESI DOKTER', 'Profesi', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('12901', 'PROFESI DOKTER GIGI', 'Profesi', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('14901', 'NERS', 'Profesi', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('48901', 'PROFESI APOTEKER', 'Profesi', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('54961', 'PROFESI DOKTER HEWAN', 'Profesi', true);
INSERT INTO program_studi(program_studi_id, nama, jenjang, aktif) VALUES ('62901', 'PROFESI AKUNTAN', 'Profesi', true); 
